import type { Metadata } from "next";
import { ShieldCheck, FileText, Gavel, Globe, Calendar, UserCheck, AlertTriangle, Calculator } from "lucide-react";
import { siteConfig } from "@/config/site";
import { StructuredData } from "@/components/seo/StructuredData";

export const metadata: Metadata = {
  title: "Terms and Conditions",
  description: "Fistotex Terms and Conditions - Legal terms governing the use of our financial calculators, news platform, and website.",
  openGraph: {
    title: "Terms and Conditions | Fistotex",
    description: "Legal terms governing the use of Fistotex financial calculators and news platform.",
    type: "website",
  },
};

const lastUpdated = new Date().toLocaleDateString("en-IN", {
  year: "numeric",
  month: "long",
  day: "numeric",
});

const sections = [
  {
    id: "acceptance",
    title: "1. Acceptance of Terms",
    icon: FileText,
    content: `
      <p>By accessing and using <strong>${siteConfig.name}</strong> ("the Site," "we," "us," or "our") at <strong>${siteConfig.url}</strong>, you ("User," "you," or "your") agree to be bound by these Terms and Conditions ("Terms"), including our <a href="/privacy-policy" className="underline">Privacy Policy</a> and <a href="/disclaimer" className="underline">Disclaimer</a>.</p>
      <p>If you do not agree with any part of these Terms, you must not use the Site.</p>
      <p>We reserve the right to modify these Terms at any time. Changes will be effective immediately upon posting with an updated "Last Updated" date. Your continued use of the Site after changes constitutes acceptance.</p>
    `,
  },
  {
    id: "description",
    title: "2. Description of Service",
    icon: ShieldCheck,
    content: `
      <p>${siteConfig.name} is an educational and informational platform providing:</p>
      <ul>
        <li><strong>Financial Calculators:</strong> Interactive tools for SIP, EMI, FD, PPF, NPS, retirement planning, and other financial calculations</li>
        <li><strong>Financial News Aggregation:</strong> Curated news from third-party Indian financial publications</li>
        <li><strong>Educational Content:</strong> Articles, guides, FAQs explaining financial concepts</li>
      </ul>
      <p>The Site is provided free of charge and does not require registration for basic use.</p>
    `,
  },
  {
    id: "license",
    title: "3. License and Use Restrictions",
    icon: UserCheck,
    content: `
      <h3>3.1 Permitted Use</h3>
      <p>We grant you a limited, non-exclusive, non-transferable, revocable license to:</p>
      <ul>
        <li>Access and use the Site for personal, non-commercial purposes</li>
        <li>Use calculators for personal financial planning and education</li>
        <li>Read news articles and educational content</li>
        <li>Share links to the Site via social media or messaging</li>
      </ul>

      <h3>3.2 Prohibited Uses</h3>
      <p>You agree not to:</p>
      <ul>
        <li>Use the Site for any unlawful purpose or in violation of any law</li>
        <li>Attempt to reverse-engineer, decompile, or extract source code</li>
        <li>Use automated tools (bots, scrapers, crawlers) to access the Site without permission</li>
        <li>Overload or disrupt the Site's servers or infrastructure</li>
        <li>Remove or modify any copyright, trademark, or proprietary notices</li>
        <li>Frame the Site or embed it in another site without permission</li>
        <li>Use calculator results for commercial advisory services without disclosure</li>
        <li>Impersonate any person or entity or misrepresent your affiliation</li>
      </ul>
    `,
  },
  {
    id: "intellectual-property",
    title: "4. Intellectual Property",
    icon: Gavel,
    content: `
      <h3>4.1 Our Content</h3>
      <p>All content on the Site including calculators, code, design, text, graphics, logos, and software (excluding third-party news content) is owned by or licensed to ${siteConfig.name} and protected by copyright, trademark, and other intellectual property laws.</p>

      <h3>4.2 Third-Party Content</h3>
      <p>News articles, images, and content from Mint, Moneycontrol, Economic Times, and other sources are the property of their respective owners. We aggregate this content under fair use / licensing principles and link to original sources. We claim no ownership over third-party content.</p>

      <h3>4.3 User Submissions</h3>
      <p>If you submit feedback, suggestions, or ideas through our contact form or otherwise, you grant us a perpetual, irrevocable, worldwide, royalty-free license to use, modify, and incorporate such submissions without compensation.</p>

      <h3>4.4 Calculator Outputs</h3>
      <p>Results generated by our calculators based on your inputs are not our intellectual property. You are free to use calculation results for personal purposes.</p>
    `,
  },
  {
    id: "calculators-terms",
    title: "5. Calculator Terms of Use",
    icon: Calculator,
    content: `
      <p>In addition to the general terms, the following apply specifically to our financial calculators:</p>
      <ul>
        <li><strong>Educational Purpose Only:</strong> Calculators are for educational and illustrative purposes. Results are mathematical estimates based on standard formulas.</li>
        <li><strong>No Guarantee of Accuracy:</strong> While we use standard formulas, we do not guarantee accuracy, completeness, or suitability for any particular purpose.</li>
        <li><strong>Assumptions Disclosed:</strong> Each calculator discloses its key assumptions. You are responsible for understanding these assumptions.</li>
        <li><strong>No Professional Advice:</strong> Calculator outputs do not constitute financial, tax, legal, or investment advice.</li>
        <li><strong>Local Processing:</strong> Calculations run in your browser. We do not see, store, or transmit your inputs or results.</li>
        <li><strong>Updates:</strong> We may update calculator formulas, assumptions, or features at any time without notice.</li>
      </ul>
    `,
  },
  {
    id: "news-terms",
    title: "6. News Content Terms",
    icon: Globe,
    content: `
      <p>Regarding news content displayed on the Site:</p>
      <ul>
        <li><strong>Aggregation Only:</strong> We aggregate headlines and summaries from RSS feeds / public APIs of news publishers.</li>
        <li><strong>Link to Source:</strong> All news items link to the original publisher's website for the full article.</li>
        <li><strong>No Endorsement:</strong> Displaying a news item does not imply endorsement of its content, views, or accuracy.</li>
        <li><strong>Publisher Terms Apply:</strong> When you click through to read full articles, you are subject to the publisher's terms of use and privacy policy.</li>
        <li><strong>Removal Requests:</strong> Publishers may request removal of their content by contacting us.</li>
      </ul>
    `,
  },
  {
    id: "user-conduct",
    title: "7. User Conduct and Responsibilities",
    icon: UserCheck,
    content: `
      <p>You are responsible for:</p>
      <ul>
        <li>Maintaining the confidentiality of any account credentials (if registration is ever added)</li>
        <li>All activities that occur under your account or device</li>
        <li>Ensuring your use of the Site complies with all applicable laws</li>
        <li>Not using the Site to transmit viruses, malware, or harmful code</li>
        <li>Not attempting to gain unauthorized access to any part of the Site</li>
      </ul>
    `,
  },
  {
    id: "disclaimers",
    title: "8. Disclaimers and No Warranties",
    icon: AlertTriangle,
    content: `
      <p><strong>THE SITE AND ALL CONTENT ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND.</strong></p>
      <p>To the fullest extent permitted by law, we disclaim all warranties, express or implied, including but not limited to:</p>
      <ul>
        <li>Warranties of merchantability, fitness for a particular purpose, and non-infringement</li>
        <li>Warranties that the Site will be uninterrupted, error-free, or secure</li>
        <li>Warranties regarding the accuracy, reliability, or completeness of any content</li>
        <li>Warranties that calculator results will match actual financial outcomes</li>
      </ul>
      <p>We do not warrant that the Site will meet your requirements or that defects will be corrected.</p>
    `,
  },
  {
    id: "limitation-liability",
    title: "9. Limitation of Liability",
    icon: ShieldCheck,
    content: `
      <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW:</p>
      <ul>
        <li><strong>No Liability for Decisions:</strong> We shall not be liable for any financial decisions you make based on Site content.</li>
        <li><strong>No Consequential Damages:</strong> We shall not be liable for any indirect, incidental, special, consequential, or punitive damages.</li>
        <li><strong>Cap on Liability:</strong> Our total aggregate liability shall not exceed ₹1,000 (Indian Rupees One Thousand) or the amount you paid to use the Site (whichever is greater).</li>
        <li><strong>Calculator Errors:</strong> We are not liable for any losses due to calculator errors, bugs, or incorrect assumptions.</li>
        <li><strong>Third-Party Content:</strong> We are not liable for any content, accuracy, or availability of third-party news or links.</li>
      </ul>
      <p>Some jurisdictions do not allow limitation of liability for certain damages. In such jurisdictions, our liability is limited to the maximum extent permitted.</p>
    `,
  },
  {
    id: "indemnification",
    title: "10. Indemnification",
    icon: Gavel,
    content: `
      <p>You agree to indemnify, defend, and hold harmless ${siteConfig.name}, its owners, officers, employees, and affiliates from and against any and all claims, damages, losses, liabilities, costs, and expenses (including reasonable legal fees) arising out of or related to:</p>
      <ul>
        <li>Your use of the Site</li>
        <li>Your violation of these Terms</li>
        <li>Your violation of any rights of a third party</li>
        <li>Any financial loss you or others incur based on your reliance on Site content</li>
        <li>Any content you submit or transmit through the Site</li>
      </ul>
    `,
  },
  {
    id: "termination",
    title: "11. Termination",
    icon: AlertTriangle,
    content: `
      <p>We may terminate or suspend your access to the Site immediately, without prior notice or liability, for any reason including breach of these Terms.</p>
      <p>Upon termination, your right to use the Site ceases immediately. Provisions that should survive termination (intellectual property, disclaimers, limitation of liability, indemnification, governing law) shall survive.</p>
    `,
  },
  {
    id: "governing-law",
    title: "12. Governing Law and Jurisdiction",
    icon: Gavel,
    content: `
      <p>These Terms shall be governed by and construed in accordance with the laws of <strong>India</strong>, without regard to conflict of law principles.</p>
      <p>Any dispute arising out of or relating to these Terms or the Site shall be subject to the <strong>exclusive jurisdiction of the courts in India</strong>.</p>
      <p>If any provision of these Terms is found to be unenforceable, the remaining provisions shall continue in full force and effect.</p>
    `,
  },
  {
    id: "changes",
    title: "13. Changes to Terms",
    icon: Calendar,
    content: `
      <p>We may modify these Terms at any time. Material changes will be indicated by updating the "Last Updated" date at the top of this page.</p>
      <p>For significant changes, we may provide additional notice (e.g., banner on the Site, email notification if you've provided contact information).</p>
      <p>Your continued use of the Site after changes constitutes acceptance of the new Terms. If you do not agree, you must stop using the Site.</p>
    `,
  },
  {
    id: "contact",
    title: "14. Contact Information",
    icon: FileText,
    content: `
      <p>If you have questions about these Terms and Conditions, please contact us:</p>
      <ul>
        <li>Email: <a href="mailto:${siteConfig.contactEmail}" className="underline">${siteConfig.contactEmail}</a></li>
        <li>Website: <a href="${siteConfig.url}/contact" className="underline">${siteConfig.url}/contact</a></li>
      </ul>
      <p>For privacy-related inquiries, see our <a href="/privacy-policy" className="underline">Privacy Policy</a>.</p>
    `,
  },
];

export default function TermsPage() {
  return (
    <div className="flex flex-col min-h-screen">
      <StructuredData type="WebPage" data={{ title: "Terms and Conditions", description: "Fistotex Terms and Conditions - Legal terms governing the use of our financial calculators, news platform, and website." }} />

      {/* Hero Section */}
      <section className="py-12 md:py-16 bg-gradient-to-b from-primary/5 to-background">
        <div className="container mx-auto px-4">
          <div className="max-w-3xl mx-auto text-center">
            <h1 className="text-4xl md:text-5xl font-bold tracking-tight text-primary mb-4">
              Terms and Conditions
            </h1>
            <p className="text-lg text-muted-foreground">
              Last updated: {lastUpdated}
            </p>
          </div>
        </div>
      </section>

      <section className="py-12 md:py-16">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            <div className="prose prose-lg max-w-none">
              {sections.map((section) => (
                <section key={section.id} id={section.id} className="mb-12 pb-8 border-b last:border-0">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="p-2 rounded-lg bg-primary/5 text-primary">
                      <section.icon className="h-5 w-5" />
                    </div>
                    <h2 className="text-2xl font-bold text-primary">{section.title}</h2>
                  </div>
                  <div className="ml-10 space-y-4 text-muted-foreground leading-relaxed">
                    {section.content.split('\n\n').map((paragraph, i) => (
                      <div key={i} dangerouslySetInnerHTML={{ __html: paragraph.trim() }} />
                    ))}
                  </div>
                </section>
              ))}
            </div>

            {/* Summary Box */}
            <div className="mt-12 p-6 rounded-xl bg-muted/50 border">
              <h3 className="font-semibold text-primary mb-4">Quick Summary</h3>
              <ul className="space-y-2 text-sm text-muted-foreground">
                <li>✓ Free to use for personal, non-commercial purposes</li>
                <li>✓ Calculators are educational tools - not financial advice</li>
                <li>✓ News content belongs to respective publishers</li>
                <li>✗ No scraping, bots, or automated access without permission</li>
                <li>✗ No commercial use of calculator outputs as advisory service</li>
                <li>✗ We're not liable for your financial decisions</li>
                <li>✓ Governed by Indian law</li>
              </ul>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}